name: Deploy Blazor App to Azure

on:
  push:
    branches:
      - master  # Change to your default branch if not "master"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Adjust to match your Blazor app's target framework

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the app
      run: dotnet publish -c Release -o publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: AzureMigrationDemoMS # Replace with your Azure App Service name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish
